// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp4nUNuSrfF1AfEzao19PO0kV0fchSs28',
    appId: '1:311522675251:web:c0bc07986cd4912239f146',
    messagingSenderId: '311522675251',
    projectId: 'monitoring-air-tambak-udang',
    authDomain: 'monitoring-air-tambak-udang.firebaseapp.com',
    databaseURL: 'https://monitoring-air-tambak-udang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-air-tambak-udang.firebasestorage.app',
    measurementId: 'G-8259S7KH7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxQF6WGvCnIYfz-sxjLsL_CsFe0k3lkl8',
    appId: '1:311522675251:android:a5b41070edb0b40839f146',
    messagingSenderId: '311522675251',
    projectId: 'monitoring-air-tambak-udang',
    databaseURL: 'https://monitoring-air-tambak-udang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-air-tambak-udang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByvIjUd9OQeCwrs2mREOinhh-Tjn2A2s8',
    appId: '1:311522675251:ios:c923aeb3ccf66f8e39f146',
    messagingSenderId: '311522675251',
    projectId: 'monitoring-air-tambak-udang',
    databaseURL: 'https://monitoring-air-tambak-udang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-air-tambak-udang.firebasestorage.app',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByvIjUd9OQeCwrs2mREOinhh-Tjn2A2s8',
    appId: '1:311522675251:ios:c923aeb3ccf66f8e39f146',
    messagingSenderId: '311522675251',
    projectId: 'monitoring-air-tambak-udang',
    databaseURL: 'https://monitoring-air-tambak-udang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-air-tambak-udang.firebasestorage.app',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp4nUNuSrfF1AfEzao19PO0kV0fchSs28',
    appId: '1:311522675251:web:3cae0a489972a95839f146',
    messagingSenderId: '311522675251',
    projectId: 'monitoring-air-tambak-udang',
    authDomain: 'monitoring-air-tambak-udang.firebaseapp.com',
    databaseURL: 'https://monitoring-air-tambak-udang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-air-tambak-udang.firebasestorage.app',
    measurementId: 'G-8092GTZP1F',
  );
}
