// ============================================================
// Entry point: main.dart
// AquaMonitor – Monitoring Kualitas Air Tambak Udang
// ============================================================

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';                      // generated by flutterfire configure
import 'providers/water_quality_provider.dart';
import 'services/notification_service.dart';
import 'services/fcm_service.dart';
import 'theme/app_theme.dart';
import 'pages/dashboard_page.dart';
import 'pages/prediction_page.dart';
import 'pages/info_page.dart';

void main() async {
  // Firebase harus diinisialisasi sebelum runApp()
  WidgetsFlutterBinding.ensureInitialized();

  // Init Firebase core — kritikal, harus berhasil
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('[main] Firebase init failed: $e');
  }

  // Init FCM & local notif — opsional, gagal tidak boleh blok app
  // (mis. rules write ditolak, Play Services tidak ada, dll)
  try {
    await FcmService().initialize();
  } catch (e) {
    debugPrint('[main] FCM init failed: $e');
  }
  try {
    await NotificationService().initialize();
  } catch (e) {
    debugPrint('[main] NotificationService init failed: $e');
  }

  // Edge-to-edge mode: buat system nav bar transparan
  SystemChrome.setEnabledSystemUIMode(
    SystemUiMode.manual,
    overlays: SystemUiOverlay.values,
  );
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    systemNavigationBarColor: AppTheme.cardWhite,
    systemNavigationBarIconBrightness: Brightness.dark,
  ));

  runApp(const AquaMonitorApp());
}


class AquaMonitorApp extends StatelessWidget {
  const AquaMonitorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => WaterQualityProvider(),
      child: MaterialApp(
        title: 'AquaMonitor – Tambak Udang',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.theme,
        home: const MainNavigationShell(),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────
// Shell: Bottom Navigation Bar wrapper
// ─────────────────────────────────────────────────────────────
class MainNavigationShell extends StatefulWidget {
  const MainNavigationShell({super.key});

  @override
  State<MainNavigationShell> createState() => _MainNavigationShellState();
}

class _MainNavigationShellState extends State<MainNavigationShell> {
  int _currentIndex = 0;

  // Parameter yang diminta saat membuka Prediksi dari Dashboard
  // (0 = Suhu, 1 = pH). PredictionPage mendengarkan perubahan nilai ini.
  final ValueNotifier<int> _predictionTab = ValueNotifier<int>(0);

  // Pages are kept alive when switching tabs via IndexedStack
  late final List<Widget> _pages = [
    DashboardPage(onOpenPrediction: _openPrediction),
    PredictionPage(parameterTab: _predictionTab),
    const InfoPage(),
  ];

  // Pindah ke tab Prediksi sekaligus memilih parameter (suhu/pH).
  void _openPrediction(int parameterIndex) {
    _predictionTab.value = parameterIndex;
    setState(() => _currentIndex = 1);
  }

  @override
  void dispose() {
    _predictionTab.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: const SystemUiOverlayStyle(
        systemNavigationBarColor: AppTheme.cardWhite,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
      child: Scaffold(
        body: IndexedStack(
          index: _currentIndex,
          children: _pages,
        ),
        bottomNavigationBar: _buildBottomNav(context),
      ),
    );
  }

  Widget _buildBottomNav(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: AppTheme.cardWhite,
        boxShadow: [
          BoxShadow(
            color: AppTheme.primaryBlue.withValues(alpha: 0.12),
            blurRadius: 16,
            offset: const Offset(0, -4),
          ),
        ],
      ),
      child: SafeArea(
        top: false,
        left: true,
        right: true,
        bottom: true,
        child: BottomNavigationBar(
          currentIndex: _currentIndex,
          onTap: (idx) => setState(() => _currentIndex = idx),
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.dashboard_rounded),
              activeIcon: Icon(Icons.dashboard_rounded),
              label: 'Dashboard',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.show_chart_rounded),
              activeIcon: Icon(Icons.show_chart_rounded),
              label: 'Prediksi',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.info_outline_rounded),
              activeIcon: Icon(Icons.info_rounded),
              label: 'Info',
            ),
          ],
        ),
      ),
    );
  }
}
