// ============================================================
// Entry point: main.dart
// AquaMonitor – Monitoring Kualitas Air Tambak Udang
// ============================================================

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';                      // generated by flutterfire configure
import 'providers/water_quality_provider.dart';
import 'services/notification_service.dart';
import 'services/fcm_service.dart';
import 'theme/app_theme.dart';
import 'pages/dashboard_page.dart';
import 'pages/prediction_page.dart';
import 'pages/info_page.dart';

void main() async {
  // Firebase harus diinisialisasi sebelum runApp()
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await FcmService().initialize();
  await NotificationService().initialize();

  // Edge-to-edge mode: buat system nav bar transparan
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    systemNavigationBarColor: Colors.transparent,
    systemNavigationBarIconBrightness: Brightness.dark,
  ));

  runApp(const AquaMonitorApp());
}


class AquaMonitorApp extends StatelessWidget {
  const AquaMonitorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => WaterQualityProvider(),
      child: MaterialApp(
        title: 'AquaMonitor – Tambak Udang',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.theme,
        home: const MainNavigationShell(),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────
// Shell: Bottom Navigation Bar wrapper
// ─────────────────────────────────────────────────────────────
class MainNavigationShell extends StatefulWidget {
  const MainNavigationShell({super.key});

  @override
  State<MainNavigationShell> createState() => _MainNavigationShellState();
}

class _MainNavigationShellState extends State<MainNavigationShell> {
  int _currentIndex = 0;

  // Pages are kept alive when switching tabs via IndexedStack
  final List<Widget> _pages = const [
    DashboardPage(),
    PredictionPage(),
    InfoPage(),
  ];

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: const SystemUiOverlayStyle(
        systemNavigationBarColor: AppTheme.cardWhite,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
      child: Scaffold(
        body: IndexedStack(
          index: _currentIndex,
          children: _pages,
        ),
        bottomNavigationBar: _buildBottomNav(context),
      ),
    );
  }

  Widget _buildBottomNav(BuildContext context) {
    final bottomPadding = MediaQuery.of(context).padding.bottom;
    return Container(
      decoration: BoxDecoration(
        color: AppTheme.cardWhite,
        boxShadow: [
          BoxShadow(
            color: AppTheme.primaryBlue.withOpacity(0.12),
            blurRadius: 16,
            offset: const Offset(0, -4),
          ),
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          BottomNavigationBar(
            currentIndex: _currentIndex,
            onTap: (idx) => setState(() => _currentIndex = idx),
            items: const [
              BottomNavigationBarItem(
                icon: Icon(Icons.dashboard_rounded),
                activeIcon: Icon(Icons.dashboard_rounded),
                label: 'Dashboard',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.show_chart_rounded),
                activeIcon: Icon(Icons.show_chart_rounded),
                label: 'Prediksi',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.info_outline_rounded),
                activeIcon: Icon(Icons.info_rounded),
                label: 'Info',
              ),
            ],
          ),
          // Isi area bawah (gesture bar) dengan warna putih
          SizedBox(
            height: bottomPadding,
            child: const ColoredBox(color: AppTheme.cardWhite),
          ),
        ],
      ),
    );
  }
}
